#!/usr/bin/env bash
# scripts/bootstrap.sh
# Run ONCE before terraform init to create the S3 state bucket and DynamoDB lock table.
# After running this, the terraform backend in main.tf will work.
#
# Usage: ./scripts/bootstrap.sh [region] [account-id]
# Example: ./scripts/bootstrap.sh us-east-1 123456789012

set -euo pipefail

REGION="${1:-us-east-1}"
ACCOUNT_ID="${2:-$(aws sts get-caller-identity --query Account --output text)}"

STATE_BUCKET="ironlog-terraform-state-${ACCOUNT_ID}"
LOCK_TABLE="ironlog-terraform-locks"

echo "╔══════════════════════════════════════════════════════╗"
echo "║     IronLog AWS Infrastructure Bootstrap             ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "Account:  ${ACCOUNT_ID}"
echo "Region:   ${REGION}"
echo "S3 Bucket:${STATE_BUCKET}"
echo ""

# ─── Create S3 bucket for Terraform state ─────────────────────
echo "▶ Creating Terraform state S3 bucket..."
if aws s3api head-bucket --bucket "${STATE_BUCKET}" 2>/dev/null; then
  echo "  ✓ Bucket already exists"
else
  if [ "${REGION}" = "us-east-1" ]; then
    aws s3api create-bucket \
      --bucket "${STATE_BUCKET}" \
      --region "${REGION}"
  else
    aws s3api create-bucket \
      --bucket "${STATE_BUCKET}" \
      --region "${REGION}" \
      --create-bucket-configuration LocationConstraint="${REGION}"
  fi
  echo "  ✓ Created ${STATE_BUCKET}"
fi

# Enable versioning
aws s3api put-bucket-versioning \
  --bucket "${STATE_BUCKET}" \
  --versioning-configuration Status=Enabled
echo "  ✓ Versioning enabled"

# Enable encryption
aws s3api put-bucket-encryption \
  --bucket "${STATE_BUCKET}" \
  --server-side-encryption-configuration '{
    "Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]
  }'
echo "  ✓ Encryption enabled"

# Block public access
aws s3api put-public-access-block \
  --bucket "${STATE_BUCKET}" \
  --public-access-block-configuration \
  "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
echo "  ✓ Public access blocked"

# ─── Create DynamoDB table for state locking ──────────────────
echo ""
echo "▶ Creating DynamoDB lock table..."
if aws dynamodb describe-table --table-name "${LOCK_TABLE}" --region "${REGION}" 2>/dev/null; then
  echo "  ✓ Table already exists"
else
  aws dynamodb create-table \
    --table-name "${LOCK_TABLE}" \
    --attribute-definitions AttributeName=LockID,AttributeType=S \
    --key-schema AttributeName=LockID,KeyType=HASH \
    --billing-mode PAY_PER_REQUEST \
    --region "${REGION}"
  echo "  ✓ Created ${LOCK_TABLE}"
fi

# ─── Create ECR repository ─────────────────────────────────────
echo ""
echo "▶ Creating ECR repository..."
if aws ecr describe-repositories --repository-names ironlog-api --region "${REGION}" 2>/dev/null; then
  echo "  ✓ ECR repository already exists"
else
  aws ecr create-repository \
    --repository-name ironlog-api \
    --image-scanning-configuration scanOnPush=true \
    --region "${REGION}"
  echo "  ✓ Created ECR repository: ironlog-api"
fi

# ─── Request ACM Certificate ──────────────────────────────────
echo ""
echo "▶ Checking for ACM certificate..."
echo "  ℹ  You need ACM certificates for:"
echo "     - api.ironlog.app (in ${REGION})"
echo "     - app.ironlog.app (in ${REGION})"
echo "     - Both domains also needed in us-east-1 for CloudFront"
echo ""
echo "  To request (run in AWS Console or CLI):"
echo "  aws acm request-certificate --domain-name '*.ironlog.app' \\"
echo "    --validation-method DNS --region us-east-1"
echo ""

# ─── Update tfvars ─────────────────────────────────────────────
echo "▶ Generating terraform.tfvars..."
cat > terraform/environments/production/terraform.tfvars <<EOF
# Generated by bootstrap.sh — update with real values before applying
aws_region    = "${REGION}"
db_username   = "ironlog"

# Update these with real ACM certificate ARNs after requesting them
acm_certificate_arn           = "arn:aws:acm:${REGION}:${ACCOUNT_ID}:certificate/REPLACE_ME"
acm_certificate_arn_us_east_1 = "arn:aws:acm:us-east-1:${ACCOUNT_ID}:certificate/REPLACE_ME"

api_domain_name = "api.ironlog.app"
app_domain_name = "app.ironlog.app"

# GitHub repository for OIDC
github_org  = "your-github-org"
github_repo = "ironlog"

team_email = "infra@ironlog.app"
EOF
echo "  ✓ Created terraform/environments/production/terraform.tfvars"

# ─── Summary ──────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  Bootstrap complete! Next steps:                     ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  1. Request ACM certificates (see above)             ║"
echo "║  2. Update terraform.tfvars with cert ARNs           ║"
echo "║  3. Set GitHub Actions secrets (see README)          ║"
echo "║  4. cd terraform/environments/production             ║"
echo "║  5. terraform init                                    ║"
echo "║  6. terraform plan                                    ║"
echo "║  7. terraform apply                                   ║"
echo "╚══════════════════════════════════════════════════════╝"
